dist: trusty
sudo: false
language: ruby
rvm:
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - jruby-9.1.12.0
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
install:
  - if [[ "$TRAVIS_RUBY_VERSION" == 2.[12] ]]; then
      rvm-exec 2.4 bundle install --jobs=3 --retry=3;
      rm Gemfile.lock;
    fi
  - bundle install --jobs=3 --retry=3
before_script:
  - if [[ "$TRAVIS_RUBY_VERSION" == 2.[12] ]]; then
      rvm-exec 2.4 rake build:converter;
    fi
script:
  - bundle exec rake test
before_deploy:
  - bundle exec rake build
deploy:
  provider: rubygems
  api_key:
    secure: "Lq/S22rljsiZBNyfSTSF9wyNiP4s4yjeeHT37vor4CgijvP8CgIJcA6UtUN+EPLe/LlZEir/p8QHTPEwAtCg2ZoU2JmN+ul8IVboHlJ19NVKT92mhKDdGe6P3yKqbqFAEoteT9MXJ3xXysSWnWFLrEPAiOmNhuh+mnPOF8uPdgw="
  on:
    rvm: 2.4
    tags: true
